# Generated by Django 4.2.4 on 2023-09-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Discription',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
