# Generated by Django 4.2.4 on 2023-09-29 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 29, 20, 10, 35, 599543, tzinfo=datetime.timezone.utc)),
        ),
    ]
