# Generated by Django 4.2.4 on 2023-09-29 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_rename_discription_article_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Description',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 29, 20, 58, 52, 331025, tzinfo=datetime.timezone.utc)),
        ),
    ]
