# Generated by Django 4.2.4 on 2023-10-23 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_published_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 23, 14, 1, 54, 594740, tzinfo=datetime.timezone.utc)),
        ),
    ]
